branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "xuehung"
- git config --global user.email "xuehung@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- set LANG=zh_TW.UTF-8
- set LC_ALL=zh_TW.UTF-8
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="codefortomorrow/foodopendata"
  - secure: UoSGQaJXT3kXXhefGnKMHTtI54Q2KB3l0R81YhxTicyOzjjQDDIL/qddrulAeg/zHHcupGiaTjTeh/W8HIeAklArpwySRyWSuq+jwSGIeSwmA06nqGe5j14SKprMMkG92d5swGqHRti4sRCul5JP/izwPX6Gbosfudql4BeNHjA=
